package com.nodemetry.backend.telemetry;

import com.nodemetry.backend.run.RunRegistry;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.jdbc.datasource.DriverManagerDataSource;
import org.springframework.jdbc.datasource.DataSourceTransactionManager;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.transaction.support.TransactionTemplate;

import javax.sql.DataSource;
import java.util.UUID;

import static org.assertj.core.api.Assertions.assertThat;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.ArgumentMatchers.anyLong;
import static org.mockito.ArgumentMatchers.eq;
import static org.mockito.Mockito.mock;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.times;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.verifyNoInteractions;

class TelemetryBatchIngestServiceTest {

    private JdbcTemplate jdbcTemplate;
    private SimpMessagingTemplate messagingTemplate;
    private RunRegistry runRegistry;
    private TelemetryBatchIngestService service;

    @BeforeEach
    void setUp() {
        DataSource dataSource = dataSource();
        jdbcTemplate = new JdbcTemplate(dataSource);
        messagingTemplate = mock(SimpMessagingTemplate.class);
        runRegistry = mock(RunRegistry.class);
        service = new TelemetryBatchIngestService(
                jdbcTemplate,
                new TransactionTemplate(new DataSourceTransactionManager(dataSource)),
                messagingTemplate,
                runRegistry,
                10,
                10
        );

        jdbcTemplate.execute("""
                create table nodes (
                    id bigint generated by default as identity primary key,
                    node_id varchar(255) not null unique,
                    status varchar(255),
                    battery float(53),
                    rssi float(53),
                    firmware_version varchar(255),
                    last_seen_at timestamp(6) with time zone,
                    created_at timestamp(6) with time zone
                )
                """);
        jdbcTemplate.execute("""
                create table sensor_readings (
                    id bigint generated by default as identity primary key,
                    message_id varchar(255) not null unique,
                    node_id varchar(255) not null,
                    run_id varchar(255),
                    temperature_raw float(53),
                    temperature_filtered float(53),
                    humidity_raw float(53),
                    humidity_filtered float(53),
                    battery float(53),
                    rssi float(53),
                    firmware_version varchar(255),
                    light float(53),
                    measured_at timestamp(6) with time zone,
                    received_at timestamp(6) with time zone
                )
                """);
    }

    @Test
    void drainOnceInsertsReadingsUpdatesLatestNodeHealthAndRecordsSavedCount() {
        service.enqueue(message("message-001", "node-001", "run-001", 87.0));
        service.enqueue(message("message-002", "node-001", "run-001", 76.0));

        assertThat(service.drainOnce()).isEqualTo(2);

        assertThat(count("sensor_readings")).isEqualTo(2);
        assertThat(count("nodes")).isEqualTo(1);
        assertThat(jdbcTemplate.queryForObject(
                "select battery from nodes where node_id = 'node-001'",
                Double.class
        )).isEqualTo(76.0);

        verify(runRegistry).recordSaved("run-001", 2L);
        verify(runRegistry, never()).recordDupe(any(), anyLong());
        verify(messagingTemplate, times(2)).convertAndSend(eq("/topic/nodes/node-001/latest"), any(SensorReadingResponse.class));
        verify(messagingTemplate, times(2)).convertAndSend(eq("/topic/readings"), any(SensorReadingResponse.class));
    }

    @Test
    void drainOnceTreatsExistingMessageIdAsDuplicate() {
        service.enqueue(message("message-001", "node-001", "run-001", 87.0));
        service.enqueue(message("message-001", "node-001", "run-001", 87.0));

        assertThat(service.drainOnce()).isEqualTo(2);

        assertThat(count("sensor_readings")).isEqualTo(1);
        verify(runRegistry).recordSaved("run-001", 1L);
        verify(runRegistry).recordDupe("run-001", 1L);
    }

    @Test
    void invalidMessagesAreDroppedBeforeDatabaseWork() {
        service.enqueue(new TelemetryMessage(
                "message-001",
                "node-001",
                "",
                23.5,
                23.5,
                48.2,
                48.2,
                87.0,
                4200.0,
                -62.0,
                "firmware-1.0.0"
        ));

        assertThat(service.drainOnce()).isEqualTo(1);

        assertThat(service.invalidCount()).isEqualTo(1);
        assertThat(count("sensor_readings")).isZero();
        assertThat(count("nodes")).isZero();
        verifyNoInteractions(runRegistry, messagingTemplate);
    }

    @Test
    void enqueueReturnsFalseAndCountsDropWhenQueueIsFull() {
        TelemetryBatchIngestService smallQueue = new TelemetryBatchIngestService(
                jdbcTemplate,
                new TransactionTemplate(new DataSourceTransactionManager(dataSource())),
                messagingTemplate,
                runRegistry,
                1,
                10
        );

        assertThat(smallQueue.enqueue(message("message-001", "node-001", "run-001", 87.0))).isTrue();
        assertThat(smallQueue.enqueue(message("message-002", "node-002", "run-001", 86.0))).isFalse();
        assertThat(smallQueue.droppedCount()).isEqualTo(1);
        assertThat(smallQueue.queuedCount()).isEqualTo(1);
    }

    private long count(String table) {
        return jdbcTemplate.queryForObject("select count(*) from " + table, Long.class);
    }

    private DataSource dataSource() {
        DriverManagerDataSource dataSource = new DriverManagerDataSource();
        dataSource.setDriverClassName("org.h2.Driver");
        dataSource.setUrl("jdbc:h2:mem:" + UUID.randomUUID() + ";MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE;DB_CLOSE_DELAY=-1");
        dataSource.setUsername("sa");
        dataSource.setPassword("");
        return dataSource;
    }

    private TelemetryMessage message(String messageId, String nodeId, String runId, Double battery) {
        return new TelemetryMessage(
                messageId,
                nodeId,
                runId,
                23.5,
                23.5,
                48.2,
                48.2,
                battery,
                4200.0,
                -62.0,
                "firmware-1.0.0"
        );
    }
}
